#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := M5Core2AWS_Hello_World_Blinky_FreeRTOS
PROJECT_VER := 1.0.0

include $(IDF_PATH)/make/project.mk

